### ISSUE TITLE
[META] ETL for Naptan

### ISSUE THREAD

**Issue by davidread** [datagovuk/api_etl#11]

**Comment by rossjones** [comment]
For the first pass at this (because it is huge) can we just do one mode of transport so that there's at least a stub there, and can be used for the basis of any geo work.

**Comment by davidread** [comment]
Going to add closest ferry port to postcode

**Comment by davidread** [comment]
We don't need bus stops for launch, I think. So can you tidy any loose ends and move it to the deploy column?

**Comment by rossjones** [comment]
I think we should close this for now until we need more ETL. What do you think?

**Comment by davidread** [comment]
Great, all done I think
